apiVersion: v1
kind: Service
metadata:
  name: k8s-init-injector-webhook
  namespace: default
spec:
  selector:
    app: k8s-init-injector-webhook
  ports:
    - port: 443
      targetPort: tls
      name: application
    - port: 80
      targetPort: metrics
      name: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-init-injector-webhook
  namespace: default
  labels:
    app: k8s-init-injector-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-init-injector-webhook
  template:
    metadata:
      labels:
        app: k8s-init-injector-webhook
    spec:
      serviceAccountName: k8s-init-injector-webhook
      securityContext:
        runAsNonRoot: true
        runAsUser: 1234
      containers:
      - name: k8s-init-injector
        image: czekish/k8s-init-injector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: tls
        - containerPort: 80
          name: metrics
        volumeMounts:
        - name: k8s-init-injector-webhook-tls-certs
          mountPath: /etc/webhook/certs/
          readOnly: true
      volumes:
      - name: k8s-init-injector-webhook-tls-certs
        secret:
          secretName: k8s-init-injector-webhook-tls