apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    k8s-init-injector-webhook-enabled: "true"
  annotations:
    k8s-init-injector/inject: "true"
    k8s-init-injector/container: "busybox-helloworld"   
spec:
  containers:
  - name: nginx
    image: nginx
