apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: injectableinitcontainer.danielstepan.cz
spec:
  group: danielstepan.cz
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                name:
                  type: string
                command:
                  type: array
                  items:
                    type: string
                args:
                  type: array
                  items:
                    type: string
                env:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                volumeMounts:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mountPath:
                        type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: injectableinitcontainer
    singular: injectableinitcontainers
    kind: InjectableInitContainer
    shortNames:
      - iic
