apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-init-injector-webhook
webhooks:
  - name: k8s-init-injector-webhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        k8s-init-injector-webhook-enabled: "true"
    clientConfig:
      service:
        name: k8s-init-injector-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lVYWNMQnFXbWF2Mm0zUDBiK0YxQmFtTlkyRi9Zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERUxNQWtHQTFVRUJoTUNRMW94RERBS0JnTlZCQWdUQTFCdlF6RUxNQWtHQTFVRUNoTUNUa0V3SGhjTgpNalF3T1RBM01UUXpOVEF3V2hjTk1qa3dPVEEyTVRRek5UQXdXakFvTVFzd0NRWURWUVFHRXdKRFdqRU1NQW9HCkExVUVDQk1EVUc5RE1Rc3dDUVlEVlFRS0V3Sk9RVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTVlBK1UvTExjcWo4U0VqUWVHVndaN3dvK2FRWlRUUjVJMStzRXhUSGNVd1pvRDQ5K08xZ1ZWSQowZ0l0WlR5NDJ5cHpVM3BkK2RKb1dTQUIyMnRkUkd3VVVYdDNJTFlJUXY2dFRqS1p4NEppcW90L0xOdWJZeFd3ClQ1T0VOMFUzd1ZNbkdpajBMUFRmei9Zd1dReHV0Um8za0ZiTTNMQWIrbGVvampVcHlNMmpnUk9oTzRMS3krdDgKYnlIYVh6cDdvZlA5K3ZmWmJaNXp1cHJqKy9hNXAvdGZ3RDhmay90azNZbDE0TWRaTXBNTzMzNERTeXlMR20wMQpzc3BPdUd0Q0hUQ0U3WjhhWm53TFBHYzZMcFoxbmZOeE5YdnVXZzc2VTc3cWtCUE14MmR6QTIyUCt6d2RmdFZqCnUyQzVxM0srVmJKRzExVkF4NXVlOXpkSm8wTXdWYzhDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUcKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkplUjhyVGlOcFpNOGNvRW5CTWdLb2xpNFY2UgpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJWc3p3ZEFaVmNGVkFocm1yUVdiWkJCaytMMnVZSERyUWw5NlVhCkZFMEp0OUR6VmpCcnlxSW92OEdEcXhreHhkTktjTWVjRncwVTJ0UUxTRXRmbVIwMFp6amdLbDhKMVBUNkFqU1UKd3hjVVFodVh6bkw4anFkUkdnK3Nrb29rRmFEWWRNakR2RUNvVXkwMEVabW9lUlpsME8raW91RC9xL0VuOUw5SApVMUpQZjhnUk40Y3VMOUtpVERkNFJocGt0K1pPV0hQc3FvRUNUWVVQemI3emtyQzVuaFJkcnptaHFhWVFNR2F1ClJlTW5UeXYxa0Jjd1lybjRxUFpIYTZBSndlSEQxNU0wcld0bzNUekFmQTl3LzRtblVUN0xnclFsRjJmWFFRaWsKMGl6SEVLZ1V2Z0cyeGswa2RyYTRLUmhPUGl0OVJHbW1kRjNiaXFWRnRwNjAzaWtsCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
