apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-init-injector-webhook
webhooks:
  - name: k8s-init-injector-webhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        k8s-init-injector-webhook-enabled: "true"
    clientConfig:
      service:
        name: k8s-init-injector-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVRkdpSVk5UFd5YU51aTJGZlpmWGxhTlQ2NFVZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qUXdPREU0Ck1UUXlOVEF3V2hjTk1qa3dPREUzTVRReU5UQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMS1ViNjlhCkNUWXNQMFhoS3h4V3VKYUtUcjMvcnF5YmF5eitkM2o3Y3ExN3pGcVpQTzIrUFNJYkg5dWx4QWJSVzVhdWZyTzQKc29janFMM3lCKy9uazErSU5aQVJMaGkrWC9sOGgvREJ0RkFJQjBZdit1TkZwb1NWWlZaeHpGWUs1Y1NTc0VGawovQmZlbHdqdVIrNUd5anBic240TGRwbFd1ZlBBb3kzNERER3RwOHZwcm1oNVphTTNVNFZaT0VrOTNzYWhpcHkxCmxpUmZTU2V1djZEOHAwMnRsWWVkS3R0Zk1pZVJqV2haUEhxUFBOMk1ZMlpKNVpGTHYyaStDYTNINkhjek9pSHMKRWxmVWdia0lmcDVLOXhsUzRxWEFIZ2VPRnYwS09nT1NuL0sxRXVYNEttZmwzdmJBSkNyZGJ4TGtCVURNL1VLSQoyajZxbHA5NFo1SllRc2NDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkRrL2p3ajM1ZVVWN1l5SzhaU1k2ditHVWZYeE1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUFPck1PblZlS0lXUnZKdnBEcXBqb3FkWXlhSXdMVDNtTGh6V25KeDN1dFhPOHJWSmlxcFc1VwpaNHhraWVFd0N3ZEdNNzJHUVQ4NS9lR2Zkc1NyNEFEaE9UUllNaCtQRzd5MGZvY005aERBdEhVV3h6cjM2SzBMCk5oSmpjMjFPdkJhYk41aGpwdU5NZmdUaXRtZE5EUEl4T09MQk1idWRpTm1oNWY4QzlrV05UNmhrT0FGTGhzaDkKUlNQV0QzSkNzUC9CNEVGblBXc1F0N2dodXVvV1JJek91ZHZVenZlVEc4Q0NXM2R5NkdnbkRtcjZ6ckFmbzdpZApkcENSVElvYXMza3N0SjhNR2QzY0g5OTIvTnlyTGRWekxvQUVyVFk0bXRxOEU5OWlBUDVWMU5kNTZhWlJnZy9yCkdxeU1NbmlCaFN2QzY1QjQ1WFVoeWhQMmpJQlpFcmRHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
